// GENERATED by scripts/sync-shared-runtime.mjs from @ruvyxa/core/route-match.
// Do not edit: edit packages/@ruvyxa/core/src/route-match.ts instead, then run
// `pnpm --filter ruvyxa sync:runtime`.
/**
 * Route matching — the single JavaScript implementation.
 *
 * Every JavaScript host that has to answer "which route is this URL?" reads
 * this module: the browser router in `@ruvyxa/react`, the serverless handler
 * in `packages/ruvyxa/runtime/serverless-handler.mjs` (via the generated
 * `runtime/route-match.mjs` copy), and the standalone Node server. A URL that
 * resolves differently in any of them renders a different page than a reload
 * of the same address, so they are not allowed to hold separate ports of these
 * rules.
 *
 * The Rust router in `crates/ruvyxa_dev_server/src/router.rs` cannot share this
 * code — it is a different language — so it is held to the same behaviour by a
 * shared case table instead: `tests/fixtures/route-match-conformance.json` is
 * replayed by both the Rust and the Node test suites.
 *
 * This module must stay dependency-free and free of Node and DOM APIs. It is
 * copied verbatim into serverless function bundles, where nothing else is
 * resolvable, and it runs in the browser.
 */
function escapeRegex(value) {
    return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
/**
 * Build the matching regex and parameter list for a route pattern.
 *
 * An optional catch-all also has to match the parent path itself (`/shop` for
 * `/shop/[[...slug]]`), which is why its slash is inside the group.
 *
 * **`\w` here is a cross-language contract, not an implementation detail.**
 * Without the `u` flag it is exactly `[A-Za-z0-9_]`, and a bracketed segment
 * whose name falls outside it is not rejected — it falls through to the literal
 * branch below and becomes an ordinary URL component. Route discovery in
 * `crates/ruvyxa_graph/src/discovery.rs` (`validate_dynamic_name`) used to accept a
 * wider set, so `app/blog/[post-id]/page.tsx` was written into the manifest as
 * a dynamic route and compiled here to the literal path `/blog/[post-id]`: a
 * route that passed `ruvyxa check`, appeared in the route table, and matched no
 * request on any host. Discovery was narrowed to this character set and now
 * refuses the folder with `RUV1002`.
 *
 * Widening any of the three patterns below without widening
 * `validate_dynamic_name` in the same change turns that silent 404 into a host
 * divergence, which is worse. `tests/fixtures/route-pattern-conformance.json`
 * is replayed by both languages and fails the one that moved.
 */
export function compilePattern(routePath) {
    if (routePath === '/') {
        return { regex: /^\/$/, paramNames: [], catchAll: null };
    }
    const segments = routePath.split('/').filter(Boolean);
    const paramNames = [];
    let catchAll = null;
    let pattern = '^';
    for (const segment of segments) {
        const optionalCatchAll = /^\[\[\.\.\.(\w+)\]\]$/.exec(segment);
        if (optionalCatchAll) {
            const name = optionalCatchAll[1];
            paramNames.push(name);
            catchAll = { name, optional: true };
            pattern += '(?:/(.*))?';
            continue;
        }
        const requiredCatchAll = /^\[\.\.\.(\w+)\]$/.exec(segment);
        if (requiredCatchAll) {
            const name = requiredCatchAll[1];
            paramNames.push(name);
            catchAll = { name, optional: false };
            pattern += '/(.+)';
            continue;
        }
        const dynamic = /^\[(\w+)\]$/.exec(segment);
        if (dynamic) {
            paramNames.push(dynamic[1]);
            pattern += '/([^/]+)';
            continue;
        }
        pattern += `/${escapeRegex(segment)}`;
    }
    pattern += '/?$';
    return { regex: new RegExp(pattern), paramNames, catchAll };
}
/**
 * Per-segment specificity: static (0) < dynamic (1) < catch-all (2) <
 * optional catch-all (3). Lower sorts first, so `/blog/new` wins over
 * `/blog/[slug]`.
 *
 * The three `\w` tests must stay identical to `compilePattern`'s: a segment
 * scored 0 here is indexed as an exact static path by
 * `createCanonicalRouteMatcher`, so a disagreement between the two would put a
 * parameterized route in the static table under its own literal spelling.
 */
export function routeSpecificity(routePath) {
    if (routePath === '/')
        return [0];
    return routePath
        .split('/')
        .filter(Boolean)
        .map((segment) => {
        if (/^\[\[\.\.\.\w+\]\]$/.test(segment))
            return 3;
        if (/^\[\.\.\.\w+\]$/.test(segment))
            return 2;
        if (/^\[\w+\]$/.test(segment))
            return 1;
        return 0;
    });
}
/** Order two specificity vectors; a shorter vector sorts before a longer one. */
export function compareSpecificity(left, right) {
    const length = Math.max(left.length, right.length);
    for (let index = 0; index < length; index++) {
        const leftScore = left[index] ?? -1;
        const rightScore = right[index] ?? -1;
        if (leftScore !== rightScore)
            return leftScore - rightScore;
    }
    return 0;
}
/**
 * Collapse a request path to the segment form the router matches against.
 *
 * `/docs/a/`, `/docs//a`, and `/docs/a` must resolve to the same route with
 * the same parameters; without this the greedy catch-all group captures the
 * trailing slash and produces a stray empty parameter segment.
 */
export function normalizeMatchPath(pathname) {
    const segments = pathname.split('/').filter(Boolean);
    return segments.length === 0 ? '/' : `/${segments.join('/')}`;
}
function hasControlCharacter(value) {
    for (const character of value) {
        const code = character.codePointAt(0);
        if (code <= 0x1f || (code >= 0x7f && code <= 0x9f))
            return true;
    }
    return false;
}
/**
 * Decode each path segment exactly once without allowing an encoded value to
 * create a route boundary or traversal component. This mirrors
 * `canonical_request_path` at the development-server request boundary.
 *
 * Returns `null` when the path is malformed or an encoded segment would change
 * the segment structure — callers treat that as "no route", never as a match.
 */
export function canonicalRoutePath(pathname) {
    if (!pathname.startsWith('/'))
        return null;
    const decoded = [];
    try {
        for (const segment of pathname.split('/').filter(Boolean)) {
            const value = decodeURIComponent(segment);
            if (value === '' ||
                value === '.' ||
                value === '..' ||
                value.includes('/') ||
                value.includes('\\') ||
                hasControlCharacter(value)) {
                return null;
            }
            decoded.push(value);
        }
    }
    catch {
        return null;
    }
    return normalizeMatchPath(`/${decoded.join('/')}`);
}
/**
 * Bind one compiled pattern's captures to named parameters.
 *
 * Split out so a host that already has a match in hand — the serverless
 * handler dispatches on its own compiled table — produces exactly the same
 * parameter object as `createRouteMatcher`.
 */
export function bindPatternParams(pattern, matched) {
    const params = {};
    for (let index = 0; index < pattern.paramNames.length; index++) {
        const name = pattern.paramNames[index];
        const value = matched[index + 1];
        if (pattern.catchAll && name === pattern.catchAll.name) {
            // An optional catch-all that captured nothing stays absent rather than
            // becoming `[]`: the documented contract is "undefined at the parent
            // route", and every host omits the key there.
            if (value) {
                params[name] = value.split('/');
            }
        }
        else {
            params[name] = value || undefined;
        }
    }
    return params;
}
/**
 * Compile a route table once and match paths already returned by
 * `canonicalRoutePath`. Hosts with raw request paths should use
 * `createRouteMatcher` so malformed and boundary-changing encodings are
 * rejected before this lookup.
 *
 * Manifest order is alphabetical, where `[` sorts before letters — matching in
 * that order would shadow `/blog/new` behind `/blog/[slug]`. Sorting by
 * specificity restores the static-first behaviour of the dev server.
 */
export function createCanonicalRouteMatcher(routes) {
    // Most application manifests are dominated by static routes. Index those
    // exact paths once so a large manifest does not execute thousands of regexes
    // for every navigation. Parameterized routes keep the proven ordered-regex
    // path below, preserving all dynamic and catch-all semantics.
    const staticRoutes = new Map();
    const parameterizedRoutes = [];
    for (const route of routes) {
        const specificity = routeSpecificity(route.path);
        if (specificity.every((segment) => segment === 0)) {
            const path = normalizeMatchPath(route.path);
            // First-write wins preserves manifest order for exact duplicate
            // patterns, matching the old stable sorted scan.
            if (!staticRoutes.has(path))
                staticRoutes.set(path, route);
            continue;
        }
        parameterizedRoutes.push({
            route,
            pattern: compilePattern(route.path),
            specificity,
        });
    }
    parameterizedRoutes.sort((left, right) => compareSpecificity(left.specificity, right.specificity));
    return function match(pathname) {
        const exact = staticRoutes.get(pathname);
        if (exact)
            return { route: exact, params: {} };
        for (const entry of parameterizedRoutes) {
            const matched = entry.pattern.regex.exec(pathname);
            if (!matched)
                continue;
            return { route: entry.route, params: bindPatternParams(entry.pattern, matched) };
        }
        return null;
    };
}
/** Compile a route table and validate/canonicalize each request before matching. */
export function createRouteMatcher(routes) {
    const matchCanonical = createCanonicalRouteMatcher(routes);
    return function match(pathname) {
        const normalized = canonicalRoutePath(pathname);
        return normalized === null ? null : matchCanonical(normalized);
    };
}
//# sourceMappingURL=route-match.js.map