import type { Meta } from '@ruvyxa/react'

import './globals.css'

/**
 * Root metadata.
 *
 * Every `meta` on a route's path is merged from this layout down to the page
 * and the most specific value wins, so `titleTemplate` here formats the title
 * of every route declared below it.
 */
export const meta: Meta = {
  title: 'Create Ruvyxa App',
  titleTemplate: '%s · Ruvyxa',
  description: 'Generated by create-ruvyxa.',
  siteName: 'Create Ruvyxa App',
  lang: 'en',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
