import "./globals.css"

export const meta = {
  title: "Create Ruvyxa App",
  description: "Generated by create-ruvyxa.",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
