//! Typed routes: `.ruvyxa/types/routes.d.ts` generation.
//!
//! The file declares one registry key per discovered page route, which narrows
//! `<Link href>` and `useRouter().push` to the routes that actually exist. See
//! `packages/@ruvyxa/react/src/route-types.ts` for the consuming types.
//!
//! Two properties matter more than the content:
//!
//! - **It is generated, never hand-edited.** `dev`, `build`, and `check` all
//!   rewrite it, so a route added in one command is visible to the editor
//!   opened alongside another.
//! - **It is inert until `tsconfig.json` includes it.** A project that never
//!   opts in keeps `RouteHref = string` and type-checks unchanged. Because that
//!   is easy to get wrong and silent when wrong, `write_route_types` reports
//!   whether the project's `tsconfig.json` covers the file, and `check` turns a
//!   miss into an actionable diagnostic rather than quietly doing nothing.

use std::path::{Path, PathBuf};

use anyhow::Context;
use ruvyxa_diagnostics::Diagnostic;
use ruvyxa_graph::{RouteKind, RouteManifest};

/// Project-relative location of the generated declaration file.
pub(crate) const ROUTE_TYPES_PATH: &str = ".ruvyxa/types/routes.d.ts";

/// The module specifier the generated file augments.
///
/// Deliberately the `routes` subpath rather than the package root: it resolves
/// to the file that *declares* `RuvyxaRouteRegistry`, and only an augmentation
/// of the declaring module merges into it.
const AUGMENTED_MODULE: &str = "@ruvyxa/react/routes";

/// Outcome of a `write_route_types` call, for callers that report to the user.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct RouteTypesOutput {
    /// Absolute path of the file that was written.
    pub(crate) path: PathBuf,
    /// Number of page routes declared.
    pub(crate) routes: usize,
    /// Whether the project `tsconfig.json` appears to include the file.
    pub(crate) included_by_tsconfig: bool,
}

/// Render the declaration file for `manifest`.
///
/// API routes are omitted. They are fetched, not navigated to, and listing them
/// as `<Link>` destinations would make a real mistake — linking to a handler
/// that returns JSON — type-check.
pub(crate) fn route_types_source(manifest: &RouteManifest) -> String {
    let mut patterns: Vec<&str> = manifest
        .routes
        .iter()
        .filter(|route| route.kind == RouteKind::Page)
        .map(|route| route.path.as_str())
        .collect();
    patterns.sort_unstable();
    patterns.dedup();

    let mut source = String::new();
    source.push_str("// Generated by Ruvyxa. Do not edit.\n");
    source.push_str("//\n");
    source.push_str(
        "// Rewritten by `ruvyxa dev`, `ruvyxa build`, and `ruvyxa check`. Delete it and\n",
    );
    source.push_str("// the next of those commands recreates it.\n\n");
    source.push_str(&format!("import type {{}} from '{AUGMENTED_MODULE}'\n\n"));
    source.push_str(&format!("declare module '{AUGMENTED_MODULE}' {{\n"));
    source.push_str("  interface RuvyxaRouteRegistry {\n");
    if patterns.is_empty() {
        source.push_str("    // No page routes were discovered.\n");
    }
    for pattern in &patterns {
        source.push_str(&format!("    {}: true\n", quote_key(pattern)));
    }
    source.push_str("  }\n");
    source.push_str("}\n");
    source
}

/// Quote a route pattern as a TypeScript string-literal property key.
///
/// Route paths come from directory names, so a quote or a backslash in one is
/// unusual but not impossible on every file system Ruvyxa runs on. Emitting it
/// raw would produce a declaration file that does not parse.
fn quote_key(pattern: &str) -> String {
    let mut quoted = String::with_capacity(pattern.len() + 2);
    quoted.push('\'');
    for ch in pattern.chars() {
        match ch {
            '\'' | '\\' => {
                quoted.push('\\');
                quoted.push(ch);
            }
            '\n' => quoted.push_str("\\n"),
            '\r' => quoted.push_str("\\r"),
            _ => quoted.push(ch),
        }
    }
    quoted.push('\'');
    quoted
}

/// Write the declaration file, creating `.ruvyxa/types/` if needed.
///
/// Rewriting an identical file is skipped: `dev` regenerates on every route
/// graph change, and touching the file's mtime for an unchanged route set would
/// wake every `tsc --watch` and editor language service watching it.
pub(crate) fn write_route_types(
    root: &Path,
    manifest: &RouteManifest,
) -> anyhow::Result<RouteTypesOutput> {
    let path = root.join(ROUTE_TYPES_PATH);
    let source = route_types_source(manifest);

    let unchanged = std::fs::read_to_string(&path).is_ok_and(|existing| existing == source);
    if !unchanged {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).with_context(|| {
                format!(
                    "failed to create route types directory {}",
                    parent.display()
                )
            })?;
        }
        std::fs::write(&path, &source)
            .with_context(|| format!("failed to write {}", path.display()))?;
    }

    Ok(RouteTypesOutput {
        path,
        routes: manifest
            .routes
            .iter()
            .filter(|route| route.kind == RouteKind::Page)
            .count(),
        included_by_tsconfig: tsconfig_includes_route_types(root),
    })
}

/// Does the project's `tsconfig.json` bring the generated file into the program?
///
/// This is a textual check, not a TypeScript resolution: reproducing `include`
/// globbing, `extends` chains, and `exclude` precedence to answer a question
/// whose only consumer is a hint would be a second implementation of tsc's file
/// selection. A project that reaches the file some other way — a `files` entry
/// in a base config, a triple-slash reference — reads as "not included" and
/// gets a hint it can ignore. The failure mode is a suggestion, never an error.
fn tsconfig_includes_route_types(root: &Path) -> bool {
    let Ok(text) = std::fs::read_to_string(root.join("tsconfig.json")) else {
        return false;
    };
    text.contains(".ruvyxa/types")
}

/// The hint shown when the declaration file exists but nothing reads it.
pub(crate) fn tsconfig_include_diagnostic(root: &Path) -> Diagnostic {
    Diagnostic::new("RUV1502", "Typed routes are generated but not type-checked")
        .explain(
            "`typedRoutes` is enabled and .ruvyxa/types/routes.d.ts was written, but tsconfig.json \
             does not include it. TypeScript never loads the file, so `<Link href>` and \
             `useRouter().push` stay typed as plain `string` and a mistyped route is not caught.",
        )
        .at_file(root.join("tsconfig.json"))
        .suggest(
            "Add \".ruvyxa/types/**/*.d.ts\" to the `include` array in tsconfig.json, \
             or set `typedRoutes: false` in ruvyxa.config.ts.",
        )
}

#[cfg(test)]
mod tests {
    use super::*;
    use ruvyxa_graph::{RenderMeta, RouteEntry, RuntimeTarget};

    fn route(path: &str, kind: RouteKind) -> RouteEntry {
        RouteEntry {
            id: path.to_string(),
            path: path.to_string(),
            kind,
            file: PathBuf::from("page.tsx"),
            layout_chain: Vec::new(),
            template_chain: Vec::new(),
            slots: Vec::new(),
            intercepts: Vec::new(),
            server_modules: Vec::new(),
            client_modules: Vec::new(),
            runtime: RuntimeTarget::Node,
            render: RenderMeta::default(),
        }
    }

    fn manifest(routes: Vec<RouteEntry>) -> RouteManifest {
        RouteManifest {
            app_dir: PathBuf::from("app"),
            routes,
            i18n: None,
        }
    }

    #[test]
    fn declares_every_page_route_sorted() {
        let source = route_types_source(&manifest(vec![
            route("/blog/[slug]", RouteKind::Page),
            route("/", RouteKind::Page),
            route("/docs/[[...path]]", RouteKind::Page),
        ]));

        let keys: Vec<&str> = source
            .lines()
            .filter_map(|line| line.trim().strip_suffix(": true"))
            .collect();
        assert_eq!(keys, vec!["'/'", "'/blog/[slug]'", "'/docs/[[...path]]'"]);
    }

    #[test]
    fn omits_api_routes() {
        // A `<Link>` to a JSON handler is a bug, so the type system must not
        // accept one.
        let source = route_types_source(&manifest(vec![
            route("/", RouteKind::Page),
            route("/api/users", RouteKind::Api),
        ]));
        assert!(source.contains("'/': true"));
        assert!(!source.contains("/api/users"));
    }

    #[test]
    fn augments_the_declaring_subpath_as_a_module() {
        // Augmenting `@ruvyxa/react` would declare an unrelated interface in the
        // barrel; the `import type {}` is what makes the file a module rather
        // than an ambient declaration that replaces the package.
        let source = route_types_source(&manifest(vec![route("/", RouteKind::Page)]));
        assert!(source.contains("import type {} from '@ruvyxa/react/routes'"));
        assert!(source.contains("declare module '@ruvyxa/react/routes' {"));
    }

    #[test]
    fn empty_route_set_still_parses() {
        let source = route_types_source(&manifest(Vec::new()));
        assert!(source.contains("interface RuvyxaRouteRegistry {"));
        assert!(source.contains("No page routes were discovered"));
    }

    #[test]
    fn escapes_quotes_in_route_paths() {
        let source = route_types_source(&manifest(vec![route("/it's", RouteKind::Page)]));
        assert!(source.contains(r"'/it\'s': true"), "{source}");
    }

    #[test]
    fn rewrites_only_when_the_route_set_changes() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();

        let first = write_route_types(root, &manifest(vec![route("/", RouteKind::Page)])).unwrap();
        let stamp = std::fs::metadata(&first.path).unwrap().modified().unwrap();

        let again = write_route_types(root, &manifest(vec![route("/", RouteKind::Page)])).unwrap();
        assert_eq!(
            std::fs::metadata(&again.path).unwrap().modified().unwrap(),
            stamp,
            "an unchanged route set must not touch the file and wake every watcher on it",
        );

        write_route_types(
            root,
            &manifest(vec![
                route("/", RouteKind::Page),
                route("/new", RouteKind::Page),
            ]),
        )
        .unwrap();
        let source = std::fs::read_to_string(&first.path).unwrap();
        assert!(source.contains("'/new': true"));
    }

    #[test]
    fn reports_whether_tsconfig_reads_the_file() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();

        std::fs::write(root.join("tsconfig.json"), r#"{"include":["app"]}"#).unwrap();
        let without = write_route_types(root, &manifest(Vec::new())).unwrap();
        assert!(!without.included_by_tsconfig);

        std::fs::write(
            root.join("tsconfig.json"),
            r#"{"include":["app",".ruvyxa/types/**/*.d.ts"]}"#,
        )
        .unwrap();
        let with = write_route_types(root, &manifest(Vec::new())).unwrap();
        assert!(with.included_by_tsconfig);
    }
}
