//! Module linker: concatenates compiled modules into a single JS string.
//!
//! Each project-local module is wrapped in a closure-style IIFE namespace so
//! that top-level declarations do not leak across module boundaries:
//!
//! ```js
//! // ── module.tsx ──
//! var __ruv_abc123__ = (function() {
//!   "use strict";
//!   var __exports = {};
//!   // … compiled JS with imports rewritten …
//!   __exports.default = MyComponent;
//!   __exports.helper = helper;
//!   return __exports;
//! })();
//! ```
//!
//! Import/export rewrites handle all ES module patterns:
//! - `import Default from "./mod"`       → `const Default = __ruv_xxx__.default`
//! - `import { a, b } from "./mod"`      → `const {a, b} = __ruv_xxx__`
//! - `import * as ns from "./mod"`       → `const ns = __ruv_xxx__`
//! - `import Default, { a } from "./mod"`→ `const Default = __ruv_xxx__.default; const {a} = __ruv_xxx__`
//! - `export { a } from "./mod"`         → re-exported via `__exports.a = __ruv_xxx__.a`
//! - `export * from "./mod"`             → `Object.assign(__exports, __ruv_xxx__)`
//! - `export default expr`              → `__exports.default = expr`
//! - `export const/function name`       → declaration + `__exports.name = name`

use std::path::{Path, PathBuf};

use blake3::hash;

use crate::compiler::CompiledModule;
use crate::{BundleInput, BundleTarget, Result};

/// Link all compiled modules into a single concatenated JS string.
pub fn link(modules: Vec<CompiledModule>, input: &BundleInput) -> Result<String> {
    let project_modules: Vec<&CompiledModule> = modules.iter().filter(|m| !m.is_external).collect();

    // Pre-calculate output capacity to avoid reallocations.
    // Each module contributes: its JS source + ~200 bytes of wrapper overhead.
    let estimated_size: usize = project_modules
        .iter()
        .map(|m| m.js.len() + 200)
        .sum::<usize>()
        + 64; // header

    let mut out = String::with_capacity(estimated_size);

    // Header comment
    out.push_str("// Generated by ruvyxa_bundler \u{2014} do not edit\n");
    out.push_str("\"use strict\";\n\n");

    for module in &project_modules {
        let id = module_id(&module.path);
        let label = module
            .path
            .file_name()
            .map(|n| n.to_string_lossy().into_owned())
            .unwrap_or_else(|| module.path.to_string_lossy().into_owned());

        out.push_str("// \u{2500}\u{2500} ");
        out.push_str(&label);
        out.push_str(" \u{2500}\u{2500}\n");

        if input.target == BundleTarget::Client {
            out.push_str("var ");
            out.push_str(&id);
            out.push_str(" = (function() {\n");
            out.push_str("  \"use strict\";\n");
            out.push_str("  var __exports = {};\n");

            rewrite_module_into(&module.js, &module.deps, &modules, &mut out, true);

            out.push_str("  return __exports;\n");
            out.push_str("})();\n\n");
        } else {
            // SSR: flat ESM concatenation — keep external imports as-is,
            // rewrite project-local imports to module namespace refs.
            rewrite_module_into(&module.js, &module.deps, &modules, &mut out, false);
            out.push('\n');
        }
    }

    Ok(out)
}

/// Deterministic identifier for a module based on its path.
///
/// Format: `__ruv_<hex16>__`
pub fn module_id(path: &Path) -> String {
    let hex = hash(path.to_string_lossy().as_bytes()).to_hex();
    format!("__ruv_{:}__", &hex[..16])
}

// ─────────────────────────────────────────────────────────────────────────────
// Import/Export rewriting engine
// ─────────────────────────────────────────────────────────────────────────────

/// Rewrite all import/export statements in a module's source.
///
/// - Project-local imports → namespace variable references
/// - Exports → `__exports.name = …` assignments
/// - External imports (not in deps) → left as-is (handled by the runtime)
fn rewrite_module_into(
    source: &str,
    deps: &[PathBuf],
    all_modules: &[CompiledModule],
    out: &mut String,
    indent: bool,
) {
    for line in source.lines() {
        let trimmed = line.trim();

        let rewritten = try_rewrite_import(trimmed, deps, all_modules)
            .or_else(|| try_rewrite_export(trimmed, deps, all_modules));

        let content = rewritten.as_deref().unwrap_or(line);

        if indent {
            if content.is_empty() {
                out.push('\n');
            } else {
                out.push_str("  ");
                out.push_str(content);
                out.push('\n');
            }
        } else {
            out.push_str(content);
            out.push('\n');
        }
    }
}

/// Try to rewrite an import statement. Returns None if the line is not an import.
fn try_rewrite_import(
    line: &str,
    deps: &[PathBuf],
    _all_modules: &[CompiledModule],
) -> Option<String> {
    if !line.starts_with("import ") {
        return None;
    }

    // Side-effect import: `import "./styles.css"` → remove (CSS handled separately)
    if line.starts_with("import \"") || line.starts_with("import '") {
        return Some(format!("// [bundled] {line}"));
    }

    // Extract the `from "specifier"` part.
    let (before_from, specifier) = split_from_specifier(line)?;

    // Find the matching dep by specifier.
    let dep_path = find_dep_for_specifier(&specifier, deps)?;
    let dep_id = module_id(dep_path);

    // Parse the import clause (the part between `import` and `from`).
    let clause = before_from.strip_prefix("import ")?.trim();

    Some(rewrite_import_clause(clause, &dep_id))
}

/// Try to rewrite an export statement. Returns None if the line is not an export.
fn try_rewrite_export(
    line: &str,
    deps: &[PathBuf],
    _all_modules: &[CompiledModule],
) -> Option<String> {
    if !line.starts_with("export ") {
        return None;
    }

    // `export default function/class name` or `export default expr`
    if line.starts_with("export default ") {
        let expr = line.strip_prefix("export default ")?.trim();
        // If it's a function/class declaration, keep the declaration and assign.
        if expr.starts_with("function ") || expr.starts_with("class ") {
            // `export default function Foo() {}` → `function Foo() {} __exports.default = Foo;`
            let name = extract_declaration_name(expr);
            if let Some(name) = name {
                return Some(format!("{expr}\n__exports.default = {name};"));
            }
        }
        // `export default expr;` → `__exports.default = expr;`
        let expr = expr.trim_end_matches(';');
        return Some(format!("__exports.default = {expr};"));
    }

    // `export { a, b } from "./mod"` — re-export from another module
    if line.contains(" from ") {
        let (before_from, specifier) = split_from_specifier(line)?;
        let dep_path = find_dep_for_specifier(&specifier, deps)?;
        let dep_id = module_id(dep_path);

        let clause = before_from.strip_prefix("export ")?.trim();

        // `export * from "./mod"` → `Object.assign(__exports, __ruv_xxx__)`
        if clause == "*" {
            return Some(format!("Object.assign(__exports, {dep_id});"));
        }

        // `export { a, b as c } from "./mod"` → `__exports.a = dep.a; __exports.c = dep.b;`
        if clause.starts_with('{') {
            let names = parse_named_bindings(clause);
            let assignments: Vec<String> = names
                .iter()
                .map(|(local, alias)| format!("__exports.{alias} = {dep_id}.{local};"))
                .collect();
            return Some(assignments.join(" "));
        }

        return None;
    }

    // `export const name = …` / `export let name = …` / `export var name = …`
    if line.starts_with("export const ")
        || line.starts_with("export let ")
        || line.starts_with("export var ")
    {
        let decl = line.strip_prefix("export ")?;
        let name = extract_var_declaration_name(decl);
        if let Some(name) = name {
            return Some(format!("{decl}\n__exports.{name} = {name};"));
        }
        return Some(decl.to_string());
    }

    // `export function name(…)` / `export class name`
    if line.starts_with("export function ")
        || line.starts_with("export class ")
        || line.starts_with("export async function ")
    {
        let decl = line.strip_prefix("export ").unwrap_or(line);
        let name = extract_declaration_name(decl);
        if let Some(name) = name {
            return Some(format!("{decl}\n__exports.{name} = {name};"));
        }
        return Some(decl.to_string());
    }

    // `export { a, b }` — named exports from current module (no `from`)
    if line.starts_with("export {") && !line.contains(" from ") {
        let clause = line.strip_prefix("export ")?.trim().trim_end_matches(';');
        let names = parse_named_bindings(clause);
        let assignments: Vec<String> = names
            .iter()
            .map(|(local, alias)| format!("__exports.{alias} = {local};"))
            .collect();
        return Some(assignments.join(" "));
    }

    None
}

/// Rewrite an import clause given the resolved module namespace ID.
///
/// Handles:
/// - `Default`                      → `const Default = dep.default`
/// - `{ a, b as c }`               → `const {a, c: b} = dep` (actually `const a = dep.a; const c = dep.b;`)
/// - `* as ns`                      → `const ns = dep`
/// - `Default, { a, b }`           → combined default + named
fn rewrite_import_clause(clause: &str, dep_id: &str) -> String {
    let clause = clause.trim();

    // `* as ns`
    if clause.starts_with("* as ") {
        let ns = clause.strip_prefix("* as ").unwrap().trim();
        return format!("const {ns} = {dep_id};");
    }

    // `{ a, b as c }` — named imports only
    if clause.starts_with('{') {
        let names = parse_named_bindings(clause);
        let bindings: Vec<String> = names
            .iter()
            .map(|(original, alias)| format!("const {alias} = {dep_id}.{original};"))
            .collect();
        return bindings.join(" ");
    }

    // `Default, { a, b }` — default + named
    if clause.contains(',') && clause.contains('{') {
        let comma_idx = clause.find(',').unwrap();
        let default_name = clause[..comma_idx].trim();
        let rest = clause[comma_idx + 1..].trim();

        let mut result = format!("const {default_name} = {dep_id}.default;");
        if rest.starts_with('{') {
            let names = parse_named_bindings(rest);
            for (original, alias) in &names {
                result.push_str(&format!(" const {alias} = {dep_id}.{original};"));
            }
        }
        return result;
    }

    // `Default` — plain default import
    if clause
        .chars()
        .all(|c| c.is_alphanumeric() || c == '_' || c == '$')
    {
        return format!("const {clause} = {dep_id}.default;");
    }

    // Fallback: comment out
    format!("// [unresolved import] {clause} from {dep_id}")
}

/// Parse `{ a, b as c, d }` into a vec of (original, alias) pairs.
fn parse_named_bindings(clause: &str) -> Vec<(String, String)> {
    let inner = clause
        .trim()
        .trim_start_matches('{')
        .trim_end_matches('}')
        .trim_end_matches(';')
        .trim();

    if inner.is_empty() {
        return Vec::new();
    }

    inner
        .split(',')
        .filter_map(|part| {
            let part = part.trim();
            if part.is_empty() {
                return None;
            }
            if let Some((original, alias)) = part.split_once(" as ") {
                Some((original.trim().to_string(), alias.trim().to_string()))
            } else {
                Some((part.to_string(), part.to_string()))
            }
        })
        .collect()
}

/// Split a line at `from "specifier"` or `from 'specifier'`.
/// Returns (everything before "from", the specifier string).
fn split_from_specifier(line: &str) -> Option<(String, String)> {
    let from_idx = line.rfind(" from ")?;
    let before = line[..from_idx].to_string();
    let after = line[from_idx + 6..].trim();

    // Extract quoted specifier.
    let specifier = extract_quoted_string(after)?;
    Some((before, specifier))
}

/// Extract a quoted string value: `"foo"` → `foo`, `'bar'` → `bar`.
fn extract_quoted_string(s: &str) -> Option<String> {
    let s = s.trim().trim_end_matches(';');
    let quote = s.chars().next()?;
    if quote != '"' && quote != '\'' {
        return None;
    }
    let end = s[1..].find(quote)?;
    Some(s[1..1 + end].to_string())
}

/// Find the dependency path that matches a given specifier.
///
/// Matches by checking if the dep path ends with the specifier (after
/// stripping extensions and normalizing separators).
fn find_dep_for_specifier<'a>(specifier: &str, deps: &'a [PathBuf]) -> Option<&'a PathBuf> {
    let normalized = specifier.replace('\\', "/");

    deps.iter().find(|dep| {
        let dep_str = dep.display().to_string().replace('\\', "/");

        // Direct path match.
        if dep_str.ends_with(&normalized) {
            return true;
        }

        // Try without extension: "./foo" matches "/project/app/foo.tsx"
        let stem = dep
            .file_stem()
            .map(|s| s.to_string_lossy().to_string())
            .unwrap_or_default();
        let spec_file = normalized.rsplit('/').next().unwrap_or(&normalized);

        if stem == spec_file {
            // Verify directory context matches.
            let spec_dir = normalized.rsplit_once('/').map(|(d, _)| d).unwrap_or("");
            if spec_dir.is_empty() || dep_str.contains(spec_dir) {
                return true;
            }
        }

        // Index file: "./utils" matches "/project/app/utils/index.tsx"
        if dep_str.ends_with("/index.ts")
            || dep_str.ends_with("/index.tsx")
            || dep_str.ends_with("/index.js")
            || dep_str.ends_with("/index.jsx")
        {
            let parent = dep
                .parent()
                .and_then(|p| p.file_name())
                .map(|n| n.to_string_lossy().to_string())
                .unwrap_or_default();
            if spec_file == parent {
                return true;
            }
        }

        false
    })
}

/// Extract the declared name from `function Name(…)` or `class Name …`.
fn extract_declaration_name(decl: &str) -> Option<String> {
    let decl = decl.trim();

    // Skip `async` prefix.
    let decl = decl.strip_prefix("async ").unwrap_or(decl);

    let rest = decl
        .strip_prefix("function* ")
        .or_else(|| decl.strip_prefix("function "))
        .or_else(|| decl.strip_prefix("class "))?;

    let name: String = rest
        .chars()
        .take_while(|c| c.is_alphanumeric() || *c == '_' || *c == '$')
        .collect();

    if name.is_empty() {
        None
    } else {
        Some(name)
    }
}

/// Extract the variable name from `const name = …` / `let name = …` / `var name = …`.
fn extract_var_declaration_name(decl: &str) -> Option<String> {
    let rest = decl
        .strip_prefix("const ")
        .or_else(|| decl.strip_prefix("let "))
        .or_else(|| decl.strip_prefix("var "))?;

    let name: String = rest
        .trim()
        .chars()
        .take_while(|c| c.is_alphanumeric() || *c == '_' || *c == '$')
        .collect();

    if name.is_empty() {
        None
    } else {
        Some(name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn module_id_is_deterministic() {
        let path = PathBuf::from("/app/foo/bar.tsx");
        let id1 = module_id(&path);
        let id2 = module_id(&path);
        assert_eq!(id1, id2);
        assert!(id1.starts_with("__ruv_"));
        assert!(id1.ends_with("__"));
    }

    #[test]
    fn rewrite_default_import() {
        let dep_id = "__ruv_test1234567890__";
        let result = rewrite_import_clause("React", dep_id);
        assert_eq!(result, "const React = __ruv_test1234567890__.default;");
    }

    #[test]
    fn rewrite_named_imports() {
        let dep_id = "__ruv_abc__";
        let result = rewrite_import_clause("{ useState, useEffect }", dep_id);
        assert!(result.contains("const useState = __ruv_abc__.useState;"));
        assert!(result.contains("const useEffect = __ruv_abc__.useEffect;"));
    }

    #[test]
    fn rewrite_named_import_with_alias() {
        let dep_id = "__ruv_abc__";
        let result = rewrite_import_clause("{ foo as bar }", dep_id);
        assert_eq!(result, "const bar = __ruv_abc__.foo;");
    }

    #[test]
    fn rewrite_namespace_import() {
        let dep_id = "__ruv_abc__";
        let result = rewrite_import_clause("* as utils", dep_id);
        assert_eq!(result, "const utils = __ruv_abc__;");
    }

    #[test]
    fn rewrite_default_plus_named() {
        let dep_id = "__ruv_abc__";
        let result = rewrite_import_clause("React, { useState }", dep_id);
        assert!(result.contains("const React = __ruv_abc__.default;"));
        assert!(result.contains("const useState = __ruv_abc__.useState;"));
    }

    #[test]
    fn parse_named_bindings_basic() {
        let names = parse_named_bindings("{ a, b, c }");
        assert_eq!(names.len(), 3);
        assert_eq!(names[0], ("a".into(), "a".into()));
        assert_eq!(names[1], ("b".into(), "b".into()));
        assert_eq!(names[2], ("c".into(), "c".into()));
    }

    #[test]
    fn parse_named_bindings_with_aliases() {
        let names = parse_named_bindings("{ foo as bar, baz }");
        assert_eq!(names[0], ("foo".into(), "bar".into()));
        assert_eq!(names[1], ("baz".into(), "baz".into()));
    }

    #[test]
    fn export_default_expression() {
        let result = try_rewrite_export("export default MyComponent;", &[], &[]);
        assert_eq!(result, Some("__exports.default = MyComponent;".into()));
    }

    #[test]
    fn export_default_function() {
        let result = try_rewrite_export("export default function Page() {}", &[], &[]);
        assert!(result.as_ref().unwrap().contains("function Page() {}"));
        assert!(result
            .as_ref()
            .unwrap()
            .contains("__exports.default = Page;"));
    }

    #[test]
    fn export_const() {
        let result = try_rewrite_export("export const helper = () => {};", &[], &[]);
        let r = result.unwrap();
        assert!(r.contains("const helper = () => {};"));
        assert!(r.contains("__exports.helper = helper;"));
    }

    #[test]
    fn export_named_bindings() {
        let result = try_rewrite_export("export { foo, bar };", &[], &[]);
        let r = result.unwrap();
        assert!(r.contains("__exports.foo = foo;"));
        assert!(r.contains("__exports.bar = bar;"));
    }

    #[test]
    fn export_star_from() {
        let dep = PathBuf::from("/app/utils.ts");
        let dep_id = module_id(&dep);
        let result = try_rewrite_export("export * from \"./utils\"", &[dep.clone()], &[]);
        assert_eq!(result, Some(format!("Object.assign(__exports, {dep_id});")));
    }

    #[test]
    fn export_named_from() {
        let dep = PathBuf::from("/app/helpers.ts");
        let dep_id = module_id(&dep);
        let result = try_rewrite_export(
            "export { foo, bar as baz } from \"./helpers\"",
            &[dep.clone()],
            &[],
        );
        let r = result.unwrap();
        assert!(r.contains(&format!("__exports.foo = {dep_id}.foo;")));
        assert!(r.contains(&format!("__exports.baz = {dep_id}.bar;")));
    }

    #[test]
    fn extract_declaration_names() {
        assert_eq!(
            extract_declaration_name("function Foo() {}"),
            Some("Foo".into())
        );
        assert_eq!(
            extract_declaration_name("class Bar extends Base {}"),
            Some("Bar".into())
        );
        assert_eq!(
            extract_declaration_name("async function fetch() {}"),
            Some("fetch".into())
        );
        assert_eq!(
            extract_declaration_name("function* gen() {}"),
            Some("gen".into())
        );
    }

    #[test]
    fn extract_var_names() {
        assert_eq!(
            extract_var_declaration_name("const foo = 1;"),
            Some("foo".into())
        );
        assert_eq!(
            extract_var_declaration_name("let bar = 'x';"),
            Some("bar".into())
        );
        assert_eq!(
            extract_var_declaration_name("var baz = {};"),
            Some("baz".into())
        );
    }

    #[test]
    fn side_effect_import_commented() {
        let result = try_rewrite_import("import \"./styles.css\"", &[], &[]);
        assert!(result.unwrap().starts_with("// [bundled]"));
    }

    #[test]
    fn split_from_specifier_works() {
        let (before, spec) = split_from_specifier("import React from \"react\"").unwrap();
        assert_eq!(before, "import React");
        assert_eq!(spec, "react");

        let (before, spec) = split_from_specifier("import { a } from './foo'").unwrap();
        assert_eq!(before, "import { a }");
        assert_eq!(spec, "./foo");
    }
}
